### ISSUE TITLE
Move package to under `src` directory?

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/cookiecutter-pypackage#17]
As presented [here](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure) it is desirable to ensure that you are never testing the 'live' version of your package, but only the installed version. Now, I'm just a simple country chicken and so can't speak to the validity of this. Thoughts?

**Comment by JacksonMaxfield** [comment]
Will look into this, forwarded it along to people in software as well to hear their thoughts.

**Comment by AetherUnbound** [comment]
A couple of thoughts on this:
This article seems fairly opinionated and is also over 5 years old - just worth noting. Several of the complaints are about stuff getting into `setup.py` and I think as time goes on an `pyproject.toml` becomes more popular this will continue to be less and less of a concern.

While having the test directory outside the module does make sense by way of forcing a distribution install of the package to test, ideally there should be no differences between the packaged version and the tested version. I'm not against it per-se, I don't see it as enough of a benefit to change that folder on every single one of our package. For this I see it as more of a "both are fine, pick one and stick with it".

As for the `src` directory, I have a couple of problems with it. _Not_ having a `src` directory and having that top level directory be the module name allows you to do this:
```
      packages=find_packages(exclude=['tests', '*.tests', '*.tests.*']),
```
One line to define where the packages are while making sure tests aren't shipped as part of the package. Alternatively, when a `src` directory is defined, you now have 3 lines that now accomplish the same thing (from the article):
```
packages=find_packages('src'),
    package_dir={'': 'src'},
    py_modules=[splitext(basename(path))[0] for path in glob('src/*.py')],
```
This seems _much_ less clear to me what's going on.

Also, `python setup.py test` is actually a really useful way to run all of the tests for a project without having to know what testing framework the package chose. It appears the author's alternative to this is "use tox" which seems insufficient.

**Comment by cdw** [comment]
Matt, you always write the most thoughtful replies.

I was confused about the src vs project slug opinion since I’ve essentially
never seen a python project use a src directory.

It seems like cookie cutter’s use of make causes tests to be easily
discoverable, too.
